# Generated by Django 4.2.1 on 2024-04-19 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='status',
            field=models.CharField(blank=True, choices=[('not assigned', 'Not Assigned'), ('assigned', 'Assigned'), ('in process', 'In Process'), ('converted', 'Converted'), ('junk lead', 'Junk Lead'), ('lost lead', 'Lost Lead')], max_length=255, null=True, verbose_name='Status of Lead'),
        ),
    ]
