# Generated by Django 4.2.1 on 2024-02-14 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0007_org_is_active'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False, verbose_name='staff status'),
        ),
    ]
