# Generated by Django 4.2.1 on 2024-02-16 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('timestamp', models.TimeField(auto_now_add=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('messageStatus', models.CharField(choices=[('SENT', 'Sent'), ('READ', 'Read'), ('DELIVERED', 'Delivered')], default='SENT', max_length=10)),
                ('isOpponent', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='WhatsappContacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wa_id', models.CharField(default='aWr1A1j3L8vteVAvgC2Qf5Ugv38jb8Zi', max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('number', models.CharField(max_length=100, unique=True)),
                ('profile_image', models.ImageField(upload_to='profile_images/')),
                ('last_message', models.TextField(default='')),
                ('messageStatus', models.CharField(choices=[('SENT', 'Sent'), ('READ', 'Read'), ('DELIVERED', 'Delivered')], default='SENT', max_length=10)),
                ('timestamp', models.TimeField(auto_now_add=True)),
            ],
        ),
    ]
