# Generated by Django 4.2.1 on 2024-02-16 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chat', '0001_initial'),
        ('leads', '0001_initial'),
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsappcontacts',
            name='contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contacts.contact'),
        ),
        migrations.AddField(
            model_name='whatsappcontacts',
            name='lead',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leads.lead'),
        ),
        migrations.AddField(
            model_name='messages',
            name='number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.whatsappcontacts', to_field='wa_id'),
        ),
    ]
