# Generated by Django 4.2.1 on 2024-02-12 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whatsappcontacts',
            name='wa_id',
            field=models.CharField(default='PpWq7RcQ0LglOvHlsRvh5WZDFsSgSodO', unique=True),
        ),
    ]
