# Generated by Django 4.2.1 on 2024-02-19 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whatsappcontacts',
            name='wa_id',
            field=models.CharField(default='J1zHRA12wti2IrWVTuJTFV9aiNOOkPuz', max_length=50, unique=True),
        ),
    ]
