# Generated by Django 4.2.1 on 2024-02-12 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_alter_whatsappcontacts_wa_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whatsappcontacts',
            name='wa_id',
            field=models.CharField(default='KEBTc9nfHYNjNPJeKp7jTNeMMPsogWtd', unique=True),
        ),
    ]
