# Generated by Django 4.2.1 on 2024-02-20 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_initial'),
        ('chat', '0003_alter_whatsappcontacts_wa_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whatsappcontacts',
            name='wa_id',
            field=models.CharField(default='8xdk5NI0mN7WGdCMhtiDSuD7LLMUEYbS', max_length=50, unique=True),
        ),
        migrations.CreateModel(
            name='OrgWhatsappMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('whatsapp_number_id', models.CharField(max_length=100, unique=True)),
                ('permanent_token', models.CharField(max_length=200, unique=True)),
                ('webhook_verification_token', models.CharField(default='1we7hU1A29dycyGEYjXAFw4XsRztarSq', max_length=50, unique=True)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.org')),
            ],
        ),
    ]
