# Generated by Django 4.2.1 on 2024-02-12 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_alter_whatsappcontacts_wa_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whatsappcontacts',
            name='number',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='whatsappcontacts',
            name='wa_id',
            field=models.CharField(default='BkNtZBFspAKO9kNizXTpLblsboW3y61J', unique=True),
        ),
    ]
