# Generated by Django 4.2.1 on 2024-02-20 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_orgwhatsappmapping_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orgwhatsappmapping',
            name='permanent_token',
            field=models.CharField(max_length=500, unique=True),
        ),
        migrations.AlterField(
            model_name='orgwhatsappmapping',
            name='webhook_verification_token',
            field=models.CharField(default='hoekL3awoqfDF4TeQRC1El31bBNuZzur', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='whatsappcontacts',
            name='wa_id',
            field=models.CharField(default='daGrzT4rU9IaGswIJ1t4hYYrfDBCl292', max_length=50, unique=True),
        ),
    ]
