# Generated by Django 4.2.1 on 2024-02-12 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_alter_whatsappcontacts_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whatsappcontacts',
            name='wa_id',
            field=models.CharField(default='RdlGmkXrUKRPuJdAP8T3GsisckhoFD4p', unique=True),
        ),
        migrations.DeleteModel(
            name='Messages',
        ),
    ]
