# Generated by Django 4.2.1 on 2024-02-12 10:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_alter_whatsappcontacts_wa_id_delete_messages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whatsappcontacts',
            name='wa_id',
            field=models.CharField(default='dRmZPSMzXwaKseut7Hq6U6H8mUnasYAX', unique=True),
        ),
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('timestamp', models.TimeField(auto_now_add=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('messageStatus', models.CharField(choices=[('SENT', 'Sent'), ('READ', 'Read'), ('DELIVERED', 'Delivered')], default='SENT', max_length=10)),
                ('isOpponent', models.BooleanField(default=False)),
                ('number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.whatsappcontacts', to_field='wa_id')),
            ],
        ),
    ]
