# Generated by Django 4.2.1 on 2024-02-21 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_alter_orgwhatsappmapping_permanent_token_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orgwhatsappmapping',
            name='url',
            field=models.CharField(default='cb5SvXMZbflNFnvDayVVUPSKvSi2pROf', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='orgwhatsappmapping',
            name='webhook_verification_token',
            field=models.CharField(default='6XT8Uh28m8RCEAuMOTiJce4xH1YHxsdS', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='whatsappcontacts',
            name='wa_id',
            field=models.CharField(default='vzjFfVDKRtz1pVH1U7i8WTNnzvxpZAJl', max_length=50, unique=True),
        ),
    ]
