# Generated by Django 4.2.1 on 2024-02-14 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_alter_whatsappcontacts_wa_id_messages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whatsappcontacts',
            name='wa_id',
            field=models.CharField(default='8CCRIaorJOJGkKx1VziNhU8z3awEyAZ7', max_length=50, unique=True),
        ),
    ]
