# Generated by Django 4.2.1 on 2024-02-22 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_alter_orgwhatsappmapping_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orgwhatsappmapping',
            name='api_refresh_token',
            field=models.CharField(default='', max_length=500, unique=True),
        ),
        migrations.AlterField(
            model_name='orgwhatsappmapping',
            name='url',
            field=models.CharField(default='tlMJg8oJOjyo8jMpIhzPVUBLWXv2Jvpg', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='orgwhatsappmapping',
            name='webhook_verification_token',
            field=models.CharField(default='ReQck7ywkeFyy3nxQcUn63EkZJKJVI4H', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='whatsappcontacts',
            name='wa_id',
            field=models.CharField(default='OzTuwG3XuQLrFUfu1t7FoxGvC7dijMGi', max_length=50, unique=True),
        ),
    ]
