# Generated by Django 4.2.1 on 2024-02-22 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0008_orgwhatsappmapping_api_refresh_token_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orgwhatsappmapping',
            name='api_refresh_token',
            field=models.CharField(max_length=500, unique=True),
        ),
        migrations.AlterField(
            model_name='orgwhatsappmapping',
            name='url',
            field=models.CharField(default='TcSv63PyGxXpPzUtNly8gPqM8zx0qZhx', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='orgwhatsappmapping',
            name='webhook_verification_token',
            field=models.CharField(default='TrOOqTFKJZ3RLC26ZdT9jDhlItQbHwBn', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='whatsappcontacts',
            name='wa_id',
            field=models.CharField(default='luKDK6ZVaEqoCFDMO2nj59X7vyEZKmPv', max_length=50, unique=True),
        ),
    ]
