# Generated by Django 4.2.1 on 2024-02-14 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0008_alter_whatsappcontacts_wa_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whatsappcontacts',
            name='wa_id',
            field=models.CharField(default='b4YljoiagXnq1sxESVWtKPFu0q1Ldj5N', max_length=50, unique=True),
        ),
    ]
