# Generated by Django 4.2.1 on 2024-03-23 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0010_orgwhatsappmapping_id_admin_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orgwhatsappmapping',
            name='url',
            field=models.CharField(default='7Otd2lFHf6QxGqCtfdWq5bZ4V9Ogiecr', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='orgwhatsappmapping',
            name='webhook_verification_token',
            field=models.CharField(default='LgNdyq0xz8Rr2SfW6E4FFJjvtUkOYVUj', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='whatsappcontacts',
            name='wa_id',
            field=models.CharField(default='DPKbeTUvmjtMAVFi1yCU0JJaJmwmJzR8', max_length=50, unique=True),
        ),
    ]
