# Generated by Django 4.2.1 on 2024-03-26 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0011_alter_orgwhatsappmapping_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orgwhatsappmapping',
            name='url',
            field=models.CharField(default='WmEkeZIU40a2YCiUvtJgRkKCtZjaRYCq', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='orgwhatsappmapping',
            name='webhook_verification_token',
            field=models.CharField(default='Xw5sdwcvEKhY2PrZI2N6bU8ffVVdlr7c', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='whatsappcontacts',
            name='wa_id',
            field=models.CharField(default='NolD6OpYEl4prTH1ZRUmmL6hwfiZiNTe', max_length=50, unique=True),
        ),
    ]
