# Generated by Django 4.2.1 on 2024-04-19 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0012_alter_orgwhatsappmapping_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orgwhatsappmapping',
            name='url',
            field=models.CharField(default='njhYsy3JjwVrMJCuxFIJyLV2GVGtpTNz', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='orgwhatsappmapping',
            name='webhook_verification_token',
            field=models.CharField(default='VbHwbpGQpoUzXX1XVAvrGgbCftIgNc5O', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='whatsappcontacts',
            name='wa_id',
            field=models.CharField(default='bHfXrcgBZKkPDZdnQH14xN8XoLbyTL9A', max_length=50, unique=True),
        ),
        migrations.CreateModel(
            name='NumberList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('list_of_numbers', models.ManyToManyField(to='chat.whatsappcontacts')),
            ],
        ),
    ]
