# Generated by Django 4.2.1 on 2024-04-19 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_initial'),
        ('chat', '0013_alter_orgwhatsappmapping_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='numberlist',
            name='org',
            field=models.ForeignKey(default='3650dad3-5670-49ee-ab5c-e490a2c791bf', on_delete=django.db.models.deletion.CASCADE, to='common.org'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='orgwhatsappmapping',
            name='url',
            field=models.CharField(default='mwolQvw9RMD9PW7aZ3TctuPBWXHwmApC', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='orgwhatsappmapping',
            name='webhook_verification_token',
            field=models.CharField(default='azflb40vMN71RnVnnGYqyo4GV9G8NYGk', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='whatsappcontacts',
            name='wa_id',
            field=models.CharField(default='vcE8FRR93SLUtLVn1k8WEM2CZoZ8f945', max_length=50, unique=True),
        ),
    ]
