# Generated by Django 4.2.1 on 2024-04-19 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunity', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opportunity',
            name='stage',
            field=models.CharField(choices=[('Enquiry Received', 'Enquiry Received'), ('Qualification', 'Qualification'), ('Quotation Sent', 'Quotation Sent'), ('Negotiation/Review', 'Negotiation/Review'), ('Closed Won', 'Closed Won'), ('Closed Lost', 'Closed Lost'), ('Closed-Lost to Competition', 'Closed-Lost to Competition')], max_length=64, verbose_name='Stage'),
        ),
    ]
